# ~/.tmuxinator/nsokc.yml

name: CMS_OKC
root: /webdev/NetLedger_CMS_OKC/cms/2
pre: tmux set-window-option -g monitor-activity off && source /webdev/.perforce
windows:
  - editor: vim
  - shell:
  - build: cd base
